language: python
python:
  - "2.7"

env:
  - DJANGO=1.4.1

# command to install dependencies
install:
  - pip install -r requirements.txt --use-mirrors

# command to run tests
script:
  - python sse_library/manage.py test library 

